### ISSUE TITLE
Maybe consolidate all of the runners into one?

### ISSUE THREAD

**Issue by ian-h-chamberlain** [ian-h-chamberlain/test-runner-3ds#6]
Instead of separate `run_console`, `run_gdb` etc., maybe we can just use all of them at once!

- The socket runner will simply fail to connect to `3dslink` if it's running in Citra or the `--server` flag wasn't used
- Either `gdbHioDevInit()` or `gdbHioDevRedirectStdStreams()` should fail if running on hardware (or they are no-ops)
- Console should basically always work, unless the test needs to own the screens / `Gfx` for some reason (in which case it should probably be an integration test, and we can control the features more carefully there).

The only oddity would be that none of them work simultaneously, so they would need to be in some kind of priority order. Maybe still have cargo features like this?

```toml
[features]
# These three output channels will be tried, in this order, to display test output.
# Failure to set up a given output stream will be ignored, so the last successful method
# will be the one ultimately used by the test. You can skip a certain method by disabling its
# corresponding feature.

default = ["console", "gdb", "socket"] # or maybe a different order/subset
console = []
gdb = []
socket = []
```
